name: Keep Render App Alive

on:
  schedule:
    - cron: '*/7 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Render App
      run: |
        # Replace with your actual Render app URL
        APP_URL="https://website-htdi.onrender.com"
        
        echo "🚀 Pinging $APP_URL at $(date)"
        
        # Make request to health endpoint
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL/health" --max-time 30)
        
        if [ "$HTTP_CODE" = "200" ]; then
          echo "✅ Success: App is alive (HTTP $HTTP_CODE)"
        else
          echo "⚠️ Warning: Received HTTP $HTTP_CODE"
        fi
        
        # Also ping the main page
        HTTP_CODE_MAIN=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL/" --max-time 30)
        echo "📱 Main page status: HTTP $HTTP_CODE_MAIN"
